### ISSUE TITLE
Reply to my message on Keybase please. Just wanna talk to you

### ISSUE THREAD

**Issue by aerisDoesCodes** [SnekJS/urban.now.sh#1]

**Comment by professor-cat** [comment]
uh i don't have any new messages on keybase.

I think you sent message to wrong keybase account or miss selected repo for issue

**Comment by aerisDoesCodes** [comment]
@professor-cat I was referring this message to Jack.. @jacc Please

**Comment by professor-cat** [comment]
by my knowledge of his status he doesn't have access to his computer or any other platform to communicate but that information from ages ago so from github events i can guess he is back and actively making stuff again on github.

@jacc i leave this for you and i am closing this issue

**Comment by professor-cat** [comment]
oh also hi @jacc welcome back.

Interesting how i didn't saw that commit you did for readme *cough* local copy is in big change *cough*

**Comment by aerisDoesCodes** [comment]
@jacc aaahhhhhh come back on discord!!!
